export const colorByType = {
    Normal: "bg-[#BCBCAC]",
    Fighting: "bg-[#BC5442]",
    Flying: "bg-[#669AFF]",
    Poison: "bg-[#AB549A]",
    Ground: "bg-[#DEBC54]",
    Rock: "bg-[#BCAC66]",
    Bug: "bg-[#ABBC1C]",
    Ghost: "bg-[#6666BC]",
    Steel: "bg-[#ABACBC]",
    Fire: "bg-[#FF421C]",
    Water: "bg-[#2F9AFF]",
    Grass: "bg-[#78CD54]",
    Electric: "bg-[#FFCD30]",
    Psychic: "bg-[#FF549A]",
    Ice: "bg-[#78DEFF]",
    Dragon: "bg-[#7866EF]",
    Dark: "bg-[#785442]",
    Fairy: "bg-[#FFACFF]",
    Unknown: "",
    Shadow: "",
  };